// Code generated by interfacer; DO NOT EDIT

package cmd

import (
	"context"
	"github.com/calyptia/api/client"
	"github.com/calyptia/api/types"
	"github.com/calyptia/api/types/legacy"
	"github.com/calyptia/go-fluentbit-config/v2"
	"net/url"
)

// Client is an interface generated for "github.com/calyptia/api/client.Client".
type Client interface {
	AWSCustomerRedirect(context.Context, string) (*url.URL, error)
	AcceptInvitation(context.Context, types.AcceptInvitation) error
	ActiveTraceSession(context.Context, string) (types.TraceSession, error)
	AddAgentMetrics(context.Context, string, []byte) error
	Agent(context.Context, string) (types.Agent, error)
	AgentConfigHistory(context.Context, string, types.AgentConfigHistoryParams) (types.AgentConfigHistory, error)
	AgentErrors(context.Context, types.ListAgentErrors) (types.AgentErrors, error)
	AgentMetrics(context.Context, string) (types.MetricsSummary, error)
	AgentMetricsByPlugin(context.Context, string) (types.MetricsSummaryPlugin, error)
	AgentMetricsOverTime(context.Context, string, types.MetricsParams) (types.MetricsOverTime, error)
	AgentMetricsOverTimeByPlugin(context.Context, string, types.MetricsParams) (types.MetricsOverTimeByPlugin, error)
	Agents(context.Context, string, types.AgentsParams) (types.Agents, error)
	AllCoreInstanceFiles(context.Context, string) ([]types.CoreInstanceFile, error)
	AllCoreInstanceSecrets(context.Context, string) ([]types.CoreInstanceSecret, error)
	Clone() *client.Client
	ClusterObject(context.Context, string) (types.ClusterObject, error)
	ClusterObjectRegex(context.Context, string) (types.ClusterObjectRegex, error)
	ClusterObjectRegexes(context.Context, types.ListClusterObjectRegexes) (types.ClusterObjectRegexes, error)
	ClusterObjects(context.Context, string, types.ClusterObjectParams) (types.ClusterObjects, error)
	ConfigSection(context.Context, string) (types.ConfigSection, error)
	ConfigSections(context.Context, string, types.ConfigSectionsParams) (types.ConfigSections, error)
	CoreInstance(context.Context, string) (types.CoreInstance, error)
	CoreInstanceCheck(context.Context, string) (types.CoreInstanceCheck, error)
	CoreInstanceChecks(context.Context, string, types.CoreInstanceChecksParams) (types.CoreInstanceChecks, error)
	CoreInstanceFiles(context.Context, types.ListCoreInstanceFiles) (types.CoreInstanceFiles, error)
	CoreInstanceMetrics(context.Context, string) (types.MetricsSummary, error)
	CoreInstanceMetricsByPlugin(context.Context, string) (types.MetricsSummaryPlugin, error)
	CoreInstanceMetricsOverTime(context.Context, string, types.MetricsParams) (types.MetricsOverTime, error)
	CoreInstanceMetricsOverTimeByPlugin(context.Context, string, types.MetricsParams) (types.MetricsOverTimeByPlugin, error)
	CoreInstancePing(context.Context, string) (types.CoreInstancePingResponse, error)
	CoreInstanceSecrets(context.Context, types.ListCoreInstanceSecrets) (types.CoreInstanceSecrets, error)
	CoreInstances(context.Context, string, types.CoreInstancesParams) (types.CoreInstances, error)
	CreateAWSContractFromToken(context.Context, types.CreateAWSContractFromToken) error
	CreateAgentError(context.Context, types.CreateAgentError) (types.Created, error)
	CreateClusterObject(context.Context, string, types.CreateClusterObject) (types.Created, error)
	CreateClusterObjectRegex(context.Context, types.CreateClusterObjectRegex) (types.Created, error)
	CreateConfigSection(context.Context, string, types.CreateConfigSection) (types.Created, error)
	CreateCoreInstance(context.Context, types.CreateCoreInstance) (types.CreatedCoreInstance, error)
	CreateCoreInstanceCheck(context.Context, string, types.Check) (types.Created, error)
	CreateCoreInstanceFile(context.Context, types.CreateCoreInstanceFile) (types.Created, error)
	CreateCoreInstanceSecret(context.Context, types.CreateCoreInstanceSecret) (types.Created, error)
	CreateEnvironment(context.Context, string, types.CreateEnvironment) (types.CreatedEnvironment, error)
	CreateFleet(context.Context, types.CreateFleet) (types.Created, error)
	CreateFleetFile(context.Context, string, types.CreateFleetFile) (types.Created, error)
	CreateIngestCheck(context.Context, string, types.CreateIngestCheck) (types.Created, error)
	CreateInvitation(context.Context, string, types.CreateInvitation) error
	CreateMetrics(context.Context, types.CreateMetrics) (types.CreatedMetrics, error)
	CreatePipeline(context.Context, string, types.CreatePipeline) (types.CreatedPipeline, error)
	CreatePipelineCheck(context.Context, string, types.CreatePipelineCheck) (types.Created, error)
	CreatePipelineFile(context.Context, string, types.CreatePipelineFile) (types.Created, error)
	CreatePipelineLog(context.Context, types.CreatePipelineLog) (types.Created, error)
	CreatePipelinePort(context.Context, string, types.CreatePipelinePort) (types.CreatedPipelinePort, error)
	CreatePipelineSecret(context.Context, string, types.CreatePipelineSecret) (types.Created, error)
	CreateProcessingRule(context.Context, types.CreateProcessingRule) (types.CreatedProcessingRule, error)
	CreateProcessingRuleTemplate(context.Context, types.CreateProcessingRuleTemplate) (types.Created, error)
	CreateProcessingRuleV1(context.Context, legacy.CreateProcessingRule) (legacy.CreatedProcessingRule, error)
	CreateProject(context.Context, types.CreateProject) (types.CreatedProject, error)
	CreateResourceProfile(context.Context, string, types.CreateResourceProfile) (types.Created, error)
	CreateSAMLMapping(context.Context, types.CreateSAMLMapping) (types.Created, error)
	CreateToken(context.Context, string, types.CreateToken) (types.Token, error)
	CreateTraceRecord(context.Context, string, types.CreateTraceRecord) (types.CreatedTraceRecord, error)
	CreateTraceSession(context.Context, string, types.CreateTraceSession) (types.Created, error)
	DeleteAgent(context.Context, string) error
	DeleteAgents(context.Context, string, ...string) error
	DeleteClusterObject(context.Context, string) error
	DeleteClusterObjectRegex(context.Context, string) error
	DeleteConfigSection(context.Context, string) error
	DeleteCoreInstance(context.Context, string) error
	DeleteCoreInstanceCheck(context.Context, string) error
	DeleteCoreInstanceFile(context.Context, string) (types.Deleted, error)
	DeleteCoreInstanceSecret(context.Context, string) (types.Deleted, error)
	DeleteCoreInstances(context.Context, string, ...string) error
	DeleteEnvironment(context.Context, string) error
	DeleteFleet(context.Context, string) (types.Deleted, error)
	DeleteFleetFile(context.Context, string) error
	DeleteIngestCheck(context.Context, string) error
	DeleteMember(context.Context, string) (types.Deleted, error)
	DeletePipeline(context.Context, string) error
	DeletePipelineCheck(context.Context, string) error
	DeletePipelineClusterObjects(context.Context, string, ...string) error
	DeletePipelineFile(context.Context, string) error
	DeletePipelineLog(context.Context, string) (types.Deleted, error)
	DeletePipelinePort(context.Context, string) error
	DeletePipelineSecret(context.Context, string) error
	DeletePipelines(context.Context, string, ...string) error
	DeleteProcessingRule(context.Context, string) error
	DeleteProcessingRuleTemplate(context.Context, string) (types.Deleted, error)
	DeleteProcessingRuleV1(context.Context, string) error
	DeleteProject(context.Context, string) (types.Deleted, error)
	DeleteResourceProfile(context.Context, string) error
	DeleteSAMLMapping(context.Context, string) (types.Deleted, error)
	DeleteToken(context.Context, string) error
	DismissAgentError(context.Context, types.DismissAgentError) (types.DismissedAgentError, error)
	Environments(context.Context, string, types.EnvironmentsParams) (types.Environments, error)
	Fleet(context.Context, types.FleetParams) (types.Fleet, error)
	FleetConfig(context.Context, string, types.FleetConfigParams) (*fluentbitconfig.Config, error)
	FleetFile(context.Context, string) (types.FleetFile, error)
	FleetFiles(context.Context, string, types.FleetFilesParams) (types.FleetFiles, error)
	FleetStatus(context.Context, types.FleetStatusParams) (types.FleetsStatus, error)
	Fleets(context.Context, types.FleetsParams) (types.Fleets, error)
	FleetsStatus(context.Context, types.FleetsStatusParams) (types.FleetsStatus, error)
	Health(context.Context) (types.Health, error)
	IngestCheck(context.Context, string) (types.IngestCheck, error)
	IngestChecks(context.Context, string, types.IngestChecksParams) (types.IngestChecks, error)
	Members(context.Context, string, types.MembersParams) (types.Memberships, error)
	Pipeline(context.Context, string, types.PipelineParams) (types.Pipeline, error)
	PipelineCheck(context.Context, string) (types.PipelineCheck, error)
	PipelineChecks(context.Context, string, types.PipelineChecksParams) (types.PipelineChecks, error)
	PipelineClusterObjects(context.Context, string, types.PipelineClusterObjectsParams) (types.ClusterObjects, error)
	PipelineConfigHistory(context.Context, string, types.PipelineConfigHistoryParams) (types.PipelineConfigHistory, error)
	PipelineFile(context.Context, string) (types.PipelineFile, error)
	PipelineFiles(context.Context, string, types.PipelineFilesParams) (types.PipelineFiles, error)
	PipelineLog(context.Context, string) (types.PipelineLog, error)
	PipelineLogs(context.Context, types.ListPipelineLogs) (types.PipelineLogs, error)
	PipelineMetadata(context.Context, string, ...string) (types.PipelineMetadata, error)
	PipelineMetrics(context.Context, string) (types.MetricsSummary, error)
	PipelineMetricsByPlugin(context.Context, string) (types.MetricsSummaryPlugin, error)
	PipelineMetricsOverTime(context.Context, string, types.MetricsParams) (types.MetricsOverTime, error)
	PipelineMetricsOverTimeByPlugin(context.Context, string, types.MetricsParams) (types.MetricsOverTimeByPlugin, error)
	PipelinePort(context.Context, string) (types.PipelinePort, error)
	PipelinePorts(context.Context, string, types.PipelinePortsParams) (types.PipelinePorts, error)
	PipelineSecret(context.Context, string) (types.PipelineSecret, error)
	PipelineSecrets(context.Context, string, types.PipelineSecretsParams) (types.PipelineSecrets, error)
	PipelineStatusHistory(context.Context, string, types.PipelineStatusHistoryParams) (types.PipelineStatusHistory, error)
	Pipelines(context.Context, types.PipelinesParams) (types.Pipelines, error)
	PreviewProcessingRule(context.Context, types.PreviewProcessingRule) ([]types.FluentBitLog, error)
	PreviewProcessingRuleV1(context.Context, legacy.PreviewProcessingRule) ([]types.FluentBitLog, error)
	ProcessingRule(context.Context, string) (types.ProcessingRule, error)
	ProcessingRuleTemplate(context.Context, string) (types.ProcessingRuleTemplate, error)
	ProcessingRuleTemplates(context.Context, types.ListProcessingRuleTemplates) (types.ProcessingRuleTemplates, error)
	ProcessingRuleV1(context.Context, string) (legacy.ProcessingRule, error)
	ProcessingRules(context.Context, types.ProcessingRulesParams) (types.ProcessingRules, error)
	ProcessingRulesV1(context.Context, legacy.ProcessingRulesParams) (legacy.ProcessingRules, error)
	Project(context.Context, string) (types.Project, error)
	Projects(context.Context, types.ProjectsParams) (types.Projects, error)
	PushAWSMarketplaceSubscriptionNotification(context.Context, types.AWSMarketplaceSubscriptionNotification) error
	RegisterAgent(context.Context, types.RegisterAgent) (types.RegisteredAgent, error)
	ResourceProfile(context.Context, string) (types.ResourceProfile, error)
	ResourceProfiles(context.Context, string, types.ResourceProfilesParams) (types.ResourceProfiles, error)
	SAMLMappings(context.Context, types.ListSAMLMappings) (types.SAMLMappings, error)
	Search(context.Context, types.SearchQuery) ([]types.SearchResult, error)
	SendVerificationEmail(context.Context) error
	SetAgentToken(string)
	SetCoreInstanceToken(string)
	SetProjectToken(string)
	SetUserAgent(string)
	TerminateActiveTraceSession(context.Context, string) (types.TerminatedTraceSession, error)
	Token(context.Context, string) (types.Token, error)
	Tokens(context.Context, string, types.TokensParams) (types.Tokens, error)
	TraceRecords(context.Context, string, types.TraceRecordsParams) (types.TraceRecords, error)
	TraceSession(context.Context, string) (types.TraceSession, error)
	TraceSessions(context.Context, string, types.TraceSessionsParams) (types.TraceSessions, error)
	UpdateAgent(context.Context, string, types.UpdateAgent) error
	UpdateClusterObject(context.Context, string, types.UpdateClusterObject) error
	UpdateClusterObjectRegex(context.Context, types.UpdateClusterObjectRegex) (types.Updated, error)
	UpdateConfigSection(context.Context, string, types.UpdateConfigSection) (types.Updated, error)
	UpdateConfigSectionSet(context.Context, string, ...string) error
	UpdateCoreInstance(context.Context, string, types.UpdateCoreInstance) error
	UpdateCoreInstanceCheck(context.Context, string, types.UpdateCoreInstanceCheck) error
	UpdateCoreInstanceFile(context.Context, types.UpdateCoreInstanceFile) (types.Updated, error)
	UpdateCoreInstanceSecret(context.Context, types.UpdateCoreInstanceSecret) (types.Updated, error)
	UpdateEnvironment(context.Context, string, types.UpdateEnvironment) error
	UpdateFleet(context.Context, types.UpdateFleet) (types.Updated, error)
	UpdateFleetFile(context.Context, string, types.UpdateFleetFile) error
	UpdateIngestCheck(context.Context, string, types.UpdateIngestCheck) error
	UpdateMember(context.Context, types.UpdateMember) error
	UpdatePipeline(context.Context, string, types.UpdatePipeline) (types.UpdatedPipeline, error)
	UpdatePipelineCheck(context.Context, string, types.UpdatePipelineCheck) error
	UpdatePipelineClusterObjects(context.Context, string, types.UpdatePipelineClusterObjects) error
	UpdatePipelineFile(context.Context, string, types.UpdatePipelineFile) error
	UpdatePipelineLog(context.Context, types.UpdatePipelineLog) (types.Updated, error)
	UpdatePipelineMetadata(context.Context, string, types.UpdatePipelineMetadata) error
	UpdatePipelinePort(context.Context, string, types.UpdatePipelinePort) error
	UpdatePipelineSecret(context.Context, string, types.UpdatePipelineSecret) error
	UpdateProcessingRule(context.Context, types.UpdateProcessingRule) (types.Updated, error)
	UpdateProcessingRuleTemplate(context.Context, types.UpdateProcessingRuleTemplate) (types.Updated, error)
	UpdateProcessingRuleV1(context.Context, legacy.UpdateProcessingRule) (types.Updated, error)
	UpdateProject(context.Context, string, types.UpdateProject) error
	UpdateResourceProfile(context.Context, string, types.UpdateResourceProfile) error
	UpdateSAMLMapping(context.Context, types.UpdateSAMLMapping) (types.Updated, error)
	UpdateToken(context.Context, types.UpdateToken) error
	UpdateTraceSession(context.Context, string, types.UpdateTraceSession) (types.Updated, error)
	ValidateFluentbitConfig(context.Context, types.ValidateFluentbitConfig) error
}
